AllTestsAdded
SamanKingDotNetDeveloper/Parking_Zone_Client pull request #10
Opened 2024-04-11 10:50 UTC by SamanKingDotNetDeveloper

2024-04-11 12:14 UTC, dotnetdew requested changes

2024-04-11 12:14 UTC, abdullokhtolibjonov commented on ParkingZoneTest/Controllers/ParkingZoneTests.cs
> +            var expectedParkingZones = new List<ParkingZone>() { _parkingZoneTest };
```suggestion
            var expectedParkingZones = new List<ViewModel>() { _parkingZoneTest };
```

2024-04-11 12:14 UTC, abdullokhtolibjonov commented on ParkingZoneTest/Controllers/ParkingZoneTests.cs
> +            Assert.IsAssignableFrom<DetailsVM>(model);
remove one of them

2024-04-11 12:14 UTC, abdullokhtolibjonov commented on ParkingZoneTest/Controllers/ParkingZoneTests.cs
> +        public void GivenViewModel_WhenCreateIsCalledToPost_ThenModelStateIsFalseReturnsVM()
```suggestion
        public void GivenCreateViewModel_WhenCreateIsCalledToPost_ThenModelStateIsFalseAndReturnsVM()
```

2024-04-11 12:14 UTC, abdullokhtolibjonov commented on ParkingZoneTest/Controllers/ParkingZoneTests.cs
> +            _controller.ModelState.AddModelError("Name", "Required");
Inline data

2024-04-11 12:14 UTC, dotnetdew commented on ParkingZoneTest/Controllers/ParkingZoneTests.cs
> +        public void GivenViewModel_WhenCreateIsCalled_ThenModelStateIsTrueReturnsRedirectToAction()
```suggestion
        public void GivenCreateVM_WhenCreateIsCalled_ThenModelStateIsTrueAndReturnsRedirectToAction()
```

2024-04-11 12:14 UTC, dotnetdew commented on ParkingZoneTest/Controllers/ParkingZoneTests.cs
> +            _service.Setup(x=>x.GetById(Id)).Returns(_parkingZoneTest);
```suggestion
            _service.Setup(x => x.GetById(Id)).Returns(_parkingZoneTest);
```

2024-04-11 12:14 UTC, dotnetdew commented on ParkingZoneTest/Controllers/ParkingZoneTests.cs
> +        public void GivenIdAndEditVM_WhenEditIsCalledToPost_ThenModelStateIsTrueReturnsRedirectToAction()
```suggestion
        public void GivenIdAndEditVM_WhenEditIsCalledToPost_ThenModelStateIsTrueAndReturnsRedirectToAction()
```

2024-04-11 12:14 UTC, dotnetdew commented on ParkingZoneTest/Controllers/ParkingZoneTests.cs
> +            EditVM editVM = new() { Id = Id};
```suggestion
            EditVM editVM = new() { Id = Id };
```

2024-04-11 12:14 UTC, dotnetdew commented on ParkingZoneTest/Controllers/ParkingZoneTests.cs
> +        public void GivenIdAndEditVM_WhenEditIsCalledToPost_ThenModelStateIsFalseReturnsView()
```suggestion
        public void GivenIdAndEditVM_WhenEditIsCalledToPost_ThenModelStateIsFalseAndReturnsView()
```

2024-04-11 12:14 UTC, dotnetdew commented on ParkingZoneTest/Controllers/ParkingZoneTests.cs
> +            EditVM editVM = new() { Id=Id};
```suggestion
            EditVM editVM = new() { Id=Id };
```

2024-04-11 12:14 UTC, dotnetdew commented on ParkingZoneTest/Controllers/ParkingZoneTests.cs
> +            _controller.ModelState.AddModelError("DateOfEstablishment", "Required");
[Inline Data], [Member data]

2024-04-11 12:14 UTC, dotnetdew commented on ParkingZoneTest/Services/ParkingZoneTests.cs
> +    public class ParkingZoneTests
```suggestion
    public class ParkingZoneServiceTests
```

2024-04-11 12:14 UTC, dotnetdew commented on ParkingZoneTest/Controllers/ParkingZoneTests.cs
> +    public class ParkingZoneTests
```suggestion
    public class ParkingZoneControllerTests
```

2024-04-11 12:14 UTC, dotnetdew commented on ParkingZoneTest/Services/ParkingZoneTests.cs
> +            // Arrange
```suggestion
            // Arrange
            var parkingZones = new List<ParkingZone>();
```

2024-04-11 12:14 UTC, dotnetdew commented on ParkingZoneTest/Services/ParkingZoneTests.cs
> +        }
JsonSerializer

2024-04-16 11:09 UTC, dotnetdew requested changes

2024-04-16 11:09 UTC, abdullokhtolibjonov commented on ParkingZoneTest/Controllers/ParkingZoneControllerTests.cs
> +            var expectedVMs = new List<ListItemVM>() {new (_parkingZoneTest) };
```suggestion
            var expectedVMs = new List<ListItemVM>() { new (_parkingZoneTest) };
```

2024-04-16 11:14 UTC, dotnetdew requested changes

2024-04-16 11:14 UTC, dotnetdew commented on ParkingZoneTest/Controllers/ParkingZoneControllerTests.cs
> +        [InlineData("Address","Required")]
```suggestion
```

2024-04-16 11:14 UTC, dotnetdew commented on ParkingZoneTest/Controllers/ParkingZoneControllerTests.cs
> +        [InlineData("DateOfEstablishment", "Required")]
```suggestion
```

2024-04-16 15:32 UTC, abdullokhtolibjonov approved these changes

2024-04-16 15:34 UTC, merged

2024-04-19 11:11 UTC, napster1991 commented on ParkingZoneApp/Areas/Admin/Views/ParkingZone/Edit.cshtml
> +            <input type="hidden" asp-for="DateOfEstablishment"/>
No need in this property on Edit view. Remove it.

2024-04-19 11:11 UTC, napster1991 commented on ParkingZoneApp/Models/ParkingZone.cs
> +        public int? Id { get; set; }
Revert! Id must not be nullable!

2024-04-19 11:11 UTC, napster1991 commented on ParkingZoneApp/Models/ParkingZone.cs
> +        public DateTime? DateOfEstablishment { get; set; }
The same.

2024-04-19 11:11 UTC, napster1991 commented on ParkingZoneApp/ViewModels/ParkingZones/DetailsVM.cs
> +        public int? Id { get; set; }
Id must not be nullable!

2024-04-19 11:11 UTC, napster1991 commented on ParkingZoneApp/ViewModels/ParkingZones/EditVM.cs
> +        public int? Id { get; set; }
The same.

2024-04-19 11:11 UTC, napster1991 commented on ParkingZoneApp/ViewModels/ParkingZones/EditVM.cs
> +        public DateTime? DateOfEstablishment { get; set; }
This property is uneditable. Remove it.

2024-04-19 11:11 UTC, napster1991 commented on ParkingZoneApp/ViewModels/ParkingZones/ListItemVM.cs
> +        public int? Id { get; set; }
Not nullable.

2024-04-19 11:11 UTC, napster1991 commented on ParkingZoneApp/ViewModels/ParkingZones/ListItemVM.cs
> +        public DateTime? DateOfEstablishment { get; set; }
Remove this property.

2024-04-19 11:11 UTC, napster1991 commented on ParkingZoneTest/ModelTests/CreateVMValidationTests.cs
> +            new object[] { "Test2", null }
I would also add a valid case and a third property (for all cases) indicating if the model is valid: `new object[] { "Test2", "test address", true }`

2024-04-19 11:11 UTC, napster1991 commented on ParkingZoneTest/ModelTests/CreateVMValidationTests.cs
> +        public void GivenInvalidItem_WhenCreatingCreateVM_ThenValidationIsFalse(string Name, string Address)
My suggestion:

`public void GivenItemToBeValidated_WhenCreatingCreateVM_ThenValidationIsPerformed(string Name, string Address, bool expectedValidationResult)`

2024-04-19 11:11 UTC, napster1991 commented on ParkingZoneTest/ModelTests/CreateVMValidationTests.cs
> +            Assert.False(result);
`Assert.IsEqual(expectedValidationResult, result);`

2024-04-19 11:11 UTC, napster1991 commented on ParkingZoneTest/ModelTests/CreateVMValidationTests.cs
> +            Assert.NotEmpty(validationResult);
This assertion can be omitted.