US023: ParkingSlot Edit Action Modified
SamanKingDotNetDeveloper/Parking_Zone_Client pull request #29
Opened 2024-05-13 20:18 UTC by SamanKingDotNetDeveloper

2024-05-14 10:23 UTC, dilmurod-rozikov approved these changes

2024-05-15 08:36 UTC, dotnetdew requested changes

2024-05-15 08:36 UTC, dotnetdew commented on ParkingZoneApp/Areas/Admin/Views/ParkingSlot/Edit.cshtml
> +@if (!Model.IsInUse)
instead of copying whole form make another solution for that

2024-05-15 08:36 UTC, dotnetdew commented on ParkingZoneApp/Areas/Admin/Views/ParkingSlot/Edit.cshtml
> +                </div>
use if here

2024-05-15 08:36 UTC, dotnetdew commented on ParkingZoneApp/Areas/Admin/Controllers/ParkingSlotController.cs
> +                return BadRequest(ModelState);
dont return bad request instead give model state error

2024-05-15 14:53 UTC, dotnetdew approved these changes

2024-05-15 16:29 UTC, merged