US025: Modify zones/index Action
SamanKingDotNetDeveloper/Parking_Zone_Client pull request #31
Opened 2024-05-17 21:10 UTC by SamDotNetDev

2024-05-18 03:25 UTC, dilmurod-rozikov requested changes

2024-05-18 03:25 UTC, dilmurod-rozikov commented on ParkingZoneApp/ViewModels/ParkingZonesVMs/ListItemVM.cs
> +        private int SlotInUse()
how about naming like this which is more informative
```suggestion
        private int CountSlotInUse()
```

2024-05-18 03:25 UTC, dilmurod-rozikov commented on ParkingZoneApp/ViewModels/ParkingZonesVMs/ListItemVM.cs
> +        private int FreeSlot()
```suggestion
        private int CountFreeSlot()
```
method names should be verb right?

2024-05-18 10:34 UTC, dilmurod-rozikov approved these changes

2024-05-20 10:41 UTC, dotnetdew requested changes

2024-05-20 10:41 UTC, dotnetdew commented on ParkingZoneApp/Areas/Admin/Controllers/ParkingSlotController.cs
> +            }
why are you returning not found?! just nothing appears index view without cards

2024-05-20 11:12 UTC, dotnetdew approved these changes

2024-05-20 11:12 UTC, merged