Feature/US004 parking zone admin crud
SamanKingDotNetDeveloper/Parking_Zone_Client pull request #4
Opened 2024-03-20 14:23 UTC by SamanKingDotNetDeveloper

2024-03-21 04:40 UTC, dotnetdew commented
Where is the Admin area? you must add these views and this controller into Admin area!

2024-03-21 07:41 UTC, dotnetdew requested changes

2024-03-21 07:41 UTC, abdullokhtolibjonov commented on ParkingZoneApp/Data/ApplicationDbContext.cs
> +        public DbSet<ParkingZoneModel> Parkin_Zone { get; set; }
```suggestion
        public DbSet<ParkingZoneModel> ParkingZone { get; set; }
```

2024-03-21 07:41 UTC, abdullokhtolibjonov commented on ParkingZoneApp/Models/ParkingZoneModel.cs
> +    public class ParkingZoneModel
```suggestion
    public class ParkingZone
```

2024-03-21 07:41 UTC, abdullokhtolibjonov commented on ParkingZoneApp/Models/ParkingZoneModel.cs
> +    public class ParkingZoneModel
no need to write Model because its staying in Models folder. isnt it?

2024-03-21 07:41 UTC, abdullokhtolibjonov commented on ParkingZoneApp/Models/ParkingZoneModel.cs
> +        public int ParkingZoneId { get; set; }
```suggestion
        public int Id { get; set; }
```

2024-03-21 07:41 UTC, abdullokhtolibjonov commented on ParkingZoneApp/Models/ParkingZoneModel.cs
> +        public int ParkingZoneId { get; set; }
if you see Id Property in ParkingZone everyone knows that this Id belongs to ParkingZone. Actually, ParkingZoneId is written in other models to define Foreign key

2024-03-21 07:41 UTC, abdullokhtolibjonov commented on ParkingZoneApp/Models/ParkingZoneModel.cs
> +        public string ParkingZoneName { get; set; }
```suggestion
        public string Name { get; set; }
```

2024-03-21 07:41 UTC, abdullokhtolibjonov commented on ParkingZoneApp/Models/ParkingZoneModel.cs
> +        public string Adress { get; set; }
```suggestion
        public string Address { get; set; }
```

2024-03-21 07:41 UTC, abdullokhtolibjonov commented on ParkingZoneApp/Models/ParkingZoneModel.cs
> +        public DateTime ParkingZoneDateOfEstablishment { get; set; }
```suggestion
        public DateTime DateOfEstablishment { get; set; }
```

2024-03-21 09:07 UTC, SamanKingDotNetDeveloper commented on ParkingZoneApp/Data/ApplicationDbContext.cs
> +        public DbSet<ParkingZoneModel> Parkin_Zone { get; set; }
Done

2024-03-21 09:11 UTC, dotnetdew requested changes

2024-03-21 09:11 UTC, abdullokhtolibjonov commented on ParkingZoneApp/Areas/Admin/Controllers/ParkingZoneController.cs
> +            return View("~/Areas/Admin/ParkingZone/Details.cshtml", parkingZoneModel);
```suggestion
            return View(parkingZoneModel);
```

2024-03-21 09:11 UTC, abdullokhtolibjonov commented on ParkingZoneApp/Areas/Admin/Controllers/ParkingZoneController.cs
> +            return View("~/Areas/Admin/ParkingZone/Create.cshtml", parkingZoneModel);
```suggestion
            return View(parkingZoneModel);
```

2024-03-21 09:11 UTC, abdullokhtolibjonov commented on ParkingZoneApp/Areas/Admin/Controllers/ParkingZoneController.cs
> +            return View("~/Areas/Admin/ParkingZone/Create.cshtml");
```suggestion
            return View();
```

2024-03-21 09:11 UTC, abdullokhtolibjonov commented on ParkingZoneApp/Areas/Admin/Controllers/ParkingZoneController.cs
> +            return View("~/Areas/Admin/ParkingZone/Edit.cshtml", parkingZoneModel);
```suggestion
            return View(parkingZoneModel);
```

2024-03-21 09:11 UTC, abdullokhtolibjonov commented on ParkingZoneApp/Areas/Admin/Controllers/ParkingZoneController.cs
> +            return View("~/Areas/Admin/ParkingZone/Edit.cshtml", parkingZoneModel);
```suggestion
            return View(parkingZoneModel);
```

2024-03-21 09:11 UTC, abdullokhtolibjonov commented on ParkingZoneApp/Areas/Admin/Controllers/ParkingZoneController.cs
> +            return View("~/Areas/Admin/ParkingZone/Delete.cshtml", parkingZoneModel);
```suggestion
            return View(parkingZoneModel);
```

2024-03-21 09:11 UTC, abdullokhtolibjonov commented on ParkingZoneApp/Areas/Admin/ParkingZone/Create.cshtml
> +    }
```suggestion
@section Scripts {
@{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
    }
```

2024-03-21 09:11 UTC, abdullokhtolibjonov commented on ParkingZoneApp/Areas/Admin/ParkingZone/Create.cshtml
> +
removw unnecessary line

2024-03-21 09:11 UTC, abdullokhtolibjonov commented on ParkingZoneApp/Areas/Admin/ParkingZone/Edit.cshtml
> +
fix spaces

2024-03-22 04:43 UTC, dotnetdew requested changes

2024-03-22 04:43 UTC, dotnetdew commented on ParkingZoneApp/Areas/Admin/Views/ParkingZone/Create.cshtml
> +
fix spaces

2024-03-22 04:43 UTC, dotnetdew commented on ParkingZoneApp/Areas/Admin/Views/ParkingZone/Create.cshtml
> +@if (SignInManager.IsSignedIn(User))
```suggestion
```

2024-03-22 04:43 UTC, dotnetdew commented on ParkingZoneApp/Areas/Admin/Views/ParkingZone/Create.cshtml
> +@if (SignInManager.IsSignedIn(User))
remove it and instead of it use [Authorize] in controller file

2024-03-22 04:43 UTC, dotnetdew commented on ParkingZoneApp/Areas/Admin/Views/ParkingZone/Delete.cshtml
> +@if (SignInManager.IsSignedIn(User))
```suggestion
```

2024-03-22 04:43 UTC, dotnetdew commented on ParkingZoneApp/Areas/Admin/Views/ParkingZone/Delete.cshtml
> +@if (SignInManager.IsSignedIn(User))
use [Authorize]

2024-03-22 04:43 UTC, dotnetdew commented on ParkingZoneApp/Areas/Admin/Views/ParkingZone/Details.cshtml
> +@if (SignInManager.IsSignedIn(User))
remove it

2024-03-22 04:43 UTC, dotnetdew commented on ParkingZoneApp/Areas/Admin/Views/ParkingZone/Edit.cshtml
> +@if (SignInManager.IsSignedIn(User))
remove

2024-03-22 04:43 UTC, dotnetdew commented on ParkingZoneApp/Areas/Admin/Views/ParkingZone/Edit.cshtml
> +
fix spaces

2024-03-22 04:43 UTC, dotnetdew commented on ParkingZoneApp/Areas/Admin/Views/ParkingZone/Index.cshtml
> +@if (SignInManager.IsSignedIn(User))
```suggestion
```

2024-03-22 04:43 UTC, dotnetdew commented on ParkingZoneApp/Areas/Admin/Views/ParkingZone/Index.cshtml
> +@if (SignInManager.IsSignedIn(User))
remove it

2024-03-22 09:12 UTC, dotnetdew approved these changes

2024-03-22 09:12 UTC, dotnetdew commented on ParkingZoneApp/Areas/Admin/Views/ParkingZone/Index.cshtml
> +}
where is the pair of this curly bracket? are u using it?

2024-03-22 09:12 UTC, dotnetdew approved these changes

2024-03-22 09:12 UTC, dotnetdew commented on ParkingZoneApp/Areas/Admin/Views/ParkingZone/Index.cshtml
> +}
where is the pair of this curly bracket? are u using it?

2024-03-22 09:16 UTC, merged